function(handleDependency dep_name submodule_name)
    find_package(${dep_name} QUIET)
    if(${dep_name}_FOUND)
        # set(${lib_name_upper}_HAS_IMPORTED_TARGETS ON)
        message(${dep_name} " Found")
    else()
        message(${dep_name} " NOT Found")
        # set(${lib_name_upper}_HAS_IMPORTED_TARGETS OFF)
        if(TARGET ${dep_name})
            message(STATUS "Using inherited ${dep} target")
        else()
            message(STATUS "Installing ${dep} via submodule")
            execute_process(COMMAND git submodule update --init --depth 1 -- external/${submodule_name}
                            WORKING_DIRECTORY ${lib_path})
            add_subdirectory(${lib_path}/external/${submodule_name} EXCLUDE_FROM_ALL)
        endif()
    endif()
endfunction()